### ISSUE TITLE
The "script" type, and put localhost:8080 as redirect URI does not work.

### ISSUE THREAD

**Issue by nami69** [Ailothaen/RedditArchiver-standalone#1]
<img width="1082" alt="스크린샷 2023-05-27 00 12 04" src="https://github.com/Ailothaen/RedditArchiver-standalone/assets/8901585/18560c79-1234-4f7f-8afb-ef1cb02ccd2d">

Hello. The instruction #2 is not working. 
Reddit won't let me write either localhost:8080 or 127.0.0.1:8080.
Is there a workaround for this?

Thanks.

**Comment by Ailothaen** [comment]
Hello,
You should include the protocol in the Redirect URI: so either `http://localhost:8080` or `http://127.0.0.1:8080`.
I indeed notice I did not include the protocol in the install documentation – thank you for the heads-up, I am going to edit it.
