### ISSUE TITLE
Error at installation

### ISSUE THREAD

**Issue by ksykes** [Ailothaen/RedditArchiver-standalone#8]
Hello,

I ran `python3 -m pip install -r requirements.txt` to install as per the instructions but am getting the following error:

```
xxxxxx@Kaits-Air ~ % python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

I am using macOS 14.6.1.

Can you please help?

**Comment by Ailothaen** [comment]
Hello!

Just to make sure, is your console currently in the correct directory?
You have to download the source code, open a console in the same directory, and run the commands from there.

**Comment by Ailothaen** [comment]
Closing this issue because of no reply.
